// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFFImMtzQpVU5dF3iwM5WLsabRZZPedg',
    appId: '1:836283907558:web:edc4519f38302b0f1d6a27',
    messagingSenderId: '836283907558',
    projectId: 'etiqa-a69c4',
    authDomain: 'etiqa-a69c4.firebaseapp.com',
    storageBucket: 'etiqa-a69c4.appspot.com',
    measurementId: 'G-90CYVF49EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaLNhIZ9b4QF5pfuh-UxK5e1LZa690Co',
    appId: '1:836283907558:android:23014047957bf87c1d6a27',
    messagingSenderId: '836283907558',
    projectId: 'etiqa-a69c4',
    storageBucket: 'etiqa-a69c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltg9CQr6s6JIO-GgBXI96RTgPNc0Bsr4',
    appId: '1:836283907558:ios:826d3d311058d2351d6a27',
    messagingSenderId: '836283907558',
    projectId: 'etiqa-a69c4',
    storageBucket: 'etiqa-a69c4.appspot.com',
    iosClientId: '836283907558-t48otea0eg3k57r91nm3onqvhm2fs29o.apps.googleusercontent.com',
    iosBundleId: 'com.emirfikri.etiqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltg9CQr6s6JIO-GgBXI96RTgPNc0Bsr4',
    appId: '1:836283907558:ios:826d3d311058d2351d6a27',
    messagingSenderId: '836283907558',
    projectId: 'etiqa-a69c4',
    storageBucket: 'etiqa-a69c4.appspot.com',
    iosClientId: '836283907558-t48otea0eg3k57r91nm3onqvhm2fs29o.apps.googleusercontent.com',
    iosBundleId: 'com.emirfikri.etiqa',
  );
}
